config/routes.rb
Rails.application.routes.draw do
  resources :locations
  get '/', to: 'locations#index', as: :root
end

app/models/location.rb
class Location < ActiveRecord::Base
  validates_presence_of :name, :area

  def coordinates
    RGeo::GeoJSON.encode(area)['coordinates'][0]
  end

  def google_coordinates
    RGeo::GeoJSON.encode(area)['coordinates'][0].map{|point| {lat: point[1], lng: point[0]}}
  end
end


app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    respond_to do |format|
      format.html  {
        if @location.save
          redirect_to locations_path, notice: 'Location was successfully created.'
        else
          render action: 'new'
        end
      }
    end
  end

  private

  def location_params
    res = params.require(:location).permit(:name, :area)
    res[:area] = RGeo::GeoJSON.decode(res[:area], json_parser: :json) if res[:area]
    res
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.slim
- flash.each do |key, value|
  .alert.alert-info
    button.close type="button" data-dismiss="alert" aria-hidden="true" ×
    = value

app/views/layouts/application.html.slim
doctype html
html
  head
    title BossTestProject
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    meta name="viewport" content="width=device-width, initial-scale=1"
    script defer=true src="https://maps.googleapis.com/maps/api/js?key=#{Rails.application.secrets.google_maps_api_key}&libraries=drawing"
  body
    .navbar.navbar-default
      .container-fluid
        .navbar-header
          .navbar-brand
            p BossTestProject
        ul.nav.navbar-nav
          li = link_to 'Locations', locations_path
          li = link_to 'New Location', new_location_path
    = render 'layouts/messages'
    = yield

app/views/locations/index.html.slim
.container-fluid
  .row
    .col-sm-12
      h3 Locations index
    .col-sm-12
      table.table
        thead
          tr
            th Name
            th Coordinates
        tbody
          - @locations.each do |loc|
            tr
              td = link_to loc.name, location_path(loc)
              td = loc.coordinates


app/views/locations/new.html.slim
.container-fluid.full-height
  .row.full-height
    .col-sm-6.col-sm-offset-3.full-height
      h3 New Location
      = simple_form_for(@location, html: { class: 'form-horizontal full-height' }) do |f|
        .row
          .col-sm-3
            = f.button :submit
          .col-sm-3.col-sm-offset-6
            a.btn.btn-default.pull-right#clear-polygon Clear polygon
        .row.full-height
          .col-sm-12.full-height
            = f.input :name
            = f.input :area, as: :string, input_html: {class: 'hidden'}
            #map
javascript:
  $(document).one('turbolinks:load', function() {
    var map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: -34.397, lng: 150.644},
      zoom: 5
    });

    var drawingManager = new google.maps.drawing.DrawingManager({
      drawingMode: google.maps.drawing.OverlayType.POLYGON,
      drawingControl: true,
      drawingControlOptions: {
        position: google.maps.ControlPosition.TOP_CENTER,
        drawingModes: [
          google.maps.drawing.OverlayType.POLYGON,
        ]
      },
      polygonOptions: {editable: true}
    });

    var selectedShape;

    function deleteSelectedShape() {
      if (selectedShape) { selectedShape.setMap(null); }
      drawingManager.setOptions({
        drawingControl: true
      });
    }

    function jsonPolygon(shape) {
      hash = {}
      hash['type'] = 'Polygon'
      hash['coordinates'] = []
      hash['coordinates'][0] = []
      shape.getPath()['b'].forEach(function(item){
        hash['coordinates'][0].push([item.lng(), item.lat()])
      })
      return JSON.stringify(hash)
    }

    google.maps.event.addListener(drawingManager, 'overlaycomplete', function(e) {
      drawingManager.setDrawingMode(null);
      drawingManager.setOptions({
        drawingControl: false
      });
      selectedShape = e.overlay;
    });

    google.maps.event.addDomListener(document.getElementById('clear-polygon'), 'click', deleteSelectedShape);

    google.maps.event.addListenerOnce(map, 'idle', function(){
      drawingManager.setMap(map);
    });

    $('form#new_location').submit(function(){
      if (selectedShape) {
        $('input#location_area').val(jsonPolygon(selectedShape));
      }
    })
  });

app/views/locations/show.html.slim
.container-fluid.full-height
  .row.full-height
    .col-sm-12
      = @location.name
    .col-sm-12.full-height
      #map
javascript:
  $(document).one('turbolinks:load', function() {
    var map = new google.maps.Map(document.getElementById('map'), {
      center: #{raw @location.google_coordinates[0].to_json},
      zoom: 5
    });

    var coordinates = #{raw @location.google_coordinates.to_json};

    // window.polygon for testing purposes
    window.polygon = new google.maps.Polygon({
      paths: coordinates,
      strokeColor: '#FF0000',
      strokeOpacity: 0.8,
      strokeWeight: 3,
      fillColor: '#FF0000',
      fillOpacity: 0.35
    });

    google.maps.event.addListenerOnce(map, 'idle', function(){
      polygon.setMap(map);
    });
  });